### ISSUE TITLE
Additional special characters

### ISSUE THREAD

**Issue by MichaelWedel** [joshburnett/scanf#2]
Hi, we've been working on integrating `scanf` into one of our projects ([here](https://github.com/DMSC-Instrument-Data/lewis/pull/227)) as an alternative for regular expressions (using `scanf_compile` to generate regexes). Many of the patterns we had defined previously were of the type `r'^\d+$'`, with `^` and `$` to make sure there's nothing else in the string.

When moving some patterns to `scanf`, we forgot to remove `^` and `$` and expected that those characters would be matched as literals. I tried to add those (and `|`) to the escaped characters in `scanf.py` and then it worked as (we) expected.

Before opening any pull request I thought I'd ask whether it was intended to work the way it's currently implemented, because with the changes it's more difficult to do the beginning and end of string matching (there would probably need to be some additional argument to add that to the generated regex).

Looking forward to your feedback! In the meantime we're going to implement a workaround on our end, because we really want to use `scanf` :)

**Comment by joshburnett** [comment]
Glad to hear that scanf is useful for you!

Go ahead and submit a pull request. You found a bug; I just forgot about escaping those characters. I'll pull it right in.

**Comment by MichaelWedel** [comment]
Thanks for your fast feedback, I've submitted the PR. If we notice anything else we'll open another issue.
