### ISSUE TITLE
Should scanf('%f, %f', '1.4,  2.34') handle leading whitespace?

### ISSUE THREAD

**Issue by davidpablocohn** [joshburnett/scanf#4]
Howdy - very grateful for the scanf.py implementation.

My recollection and perusal of the C docs is that scanf should handle leading whitespace for numeric values. Doesn't look like the current implementation does that. I've made minor mods to the defs, e.g.:

    ("%(\d)[di]", "([+-]?\d{%s})", int),
    ("%\*(\d)[di]", "(?:[+-]?\d{%s})", None),
===>
    ("%(\d)[di]", "\s*([+-]?\d{%s})", int),
    ("%\*(\d)[di]", "\s*(?:[+-]?\d{%s})", None),

Which seems to work (I'll admit that some parts of the code remain mysterious to me). Shall I file a change and a pull request? (I'd also love it if it could handle NaNs and Inf, but I have no idea how to implement that, and can work around it in my enclosing code.

Thanks again,
 -pablo

**Comment by joshburnett** [comment]
Apologies for taking a little while to reply here.

I'm not quite sure what you mean about needing to handle leading whitespace.  In my testing, it already does:

```python
>>> from scanf import scanf
>>> scanf('%f, %f', '1.4, 2.34')
(1.4, 2.34)
>>> scanf('%f, %f', '  1.4, 2.34')
(1.4, 2.34)
>>> scanf('%d, %f', '  1, 2.34')
(1, 2.34)
```

If you could please give me an example that doesn't work the way you'd expect it to work, I'm happy to see what we can do to fix it. Glad to know that other people are finding this library helpful!

**Comment by davidpablocohn** [comment]
Dang - you're right. Problem was in my test setup (facepalm). So sorry for the false alarm.  And thanks again for the library!
