### ISSUE TITLE
Unit tests fail

### ISSUE THREAD

**Issue by prittenhouse** [joshburnett/scanf#5]
Hi,

Thanks for creating this library, it's very useful.   Frankly I don't know why it isn't part of the standard Python distribution.

One thing I did notice though is that the unit tests don't all pass.  I made some updates to fix them (see attached).  I also noticed that there is a potential issue with the cache now that the collapse whitespace flag has been added.  Since the cache ignores the flag you can end up getting back the wrong results.  I have included a fix for that too but I'm not sure its the best approach but it should work.   If you would like me to generate a pull request with my changes let me know.

Thanks again for the package
Phil
[scanf.zip](https://github.com/joshburnett/scanf/files/1720435/scanf.zip)

**Comment by joshburnett** [comment]
Awesome, thanks for your feeback (and bug fixes)!  I'll take a look at the changes and hopefully get them in pretty soon.  Busy week here. :-)

**Comment by joshburnett** [comment]
Fixed, thanks
